export interface CpuBus { read(address: number): number; write(address: number, value: number): void; }
const C=1,Z=2,I=4,D=8,B=16,U=32,V=64,N=128;
export class Cpu6502 {
  a=0; x=0; y=0; sp=0xfd; p=U|I; pc=0; cycles=0; unknownOpcodes=0; lastUnknownOpcode=-1; readonly unknownOpcodeCounts=new Uint32Array(256);
  constructor(private readonly bus: CpuBus) {}
  reset(): void { this.sp=0xfd; this.p=U|I; this.pc=this.read16(0xfffc); this.cycles=0; this.unknownOpcodes=0; this.lastUnknownOpcode=-1; this.unknownOpcodeCounts.fill(0); }
  save(): number[]{return [this.a,this.x,this.y,this.sp,this.p,this.pc&255,this.pc>>>8,this.cycles&255,(this.cycles>>>8)&255,(this.cycles>>>16)&255,(this.cycles>>>24)&255];}
  load(v:number[]): void {[this.a,this.x,this.y,this.sp,this.p]=v; this.pc=v[5]|(v[6]<<8); this.cycles=v[7]|(v[8]<<8)|(v[9]<<16)|(v[10]<<24);}
  irq(): void { if (!(this.p&I)) this.interrupt(0xfffe); }
  nmi(): void { this.interrupt(0xfffa); }
  step(): number { const op=this.fetch(); let used=2; switch(op){
    case 0xea: break; case 0xa9: this.a=this.imm(); used=2; break; case 0xa2: this.x=this.imm(); used=2; break; case 0xa0: this.y=this.imm(); used=2; break; case 0xa1: this.a=this.bus.read(this.indX()); this.nz(this.a); used=6; break; case 0xb1: this.a=this.bus.read(this.indY()); this.nz(this.a); used=5; break; case 0xb5: this.a=this.bus.read(this.zpx()); this.nz(this.a); used=4; break; case 0xb6: this.x=this.bus.read(this.zpy()); this.nz(this.x); used=4; break; case 0xb4: this.y=this.bus.read(this.zpx()); this.nz(this.y); used=4; break; case 0xbe: this.x=this.bus.read(this.absy()); this.nz(this.x); used=4; break; case 0xb9: this.a=this.bus.read(this.absy()); this.nz(this.a); used=4; break; case 0xae: this.x=this.bus.read(this.abs()); this.nz(this.x); used=4; break; case 0xbc: this.y=this.bus.read(this.absx()); this.nz(this.y); used=4; break;
    case 0x8d: this.bus.write(this.abs(),this.a); used=4; break; case 0x8e: this.bus.write(this.abs(),this.x); used=4; break; case 0x8c: this.bus.write(this.abs(),this.y); used=4; break; case 0x81: this.bus.write(this.indX(),this.a); used=6; break; case 0x91: this.bus.write(this.indY(),this.a); used=6; break; case 0x95: this.bus.write(this.zpx(),this.a); used=4; break; case 0x96: this.bus.write(this.zpy(),this.x); used=4; break; case 0x94: this.bus.write(this.zpx(),this.y); used=4; break; case 0x9d: this.bus.write(this.absx(),this.a); used=5; break; case 0x99: this.bus.write(this.absy(),this.a); used=5; break;
    case 0xad: this.a=this.bus.read(this.abs()); this.nz(this.a); used=4; break; case 0xbd: {const b=this.abs()+this.x; this.a=this.bus.read(b); this.nz(this.a); used=4+(b>0xffff?0:0); break;}
    case 0xe8: this.x=(this.x+1)&255; this.nz(this.x); used=2; break; case 0xca: this.x=(this.x-1)&255; this.nz(this.x); used=2; break; case 0xc8: this.y=(this.y+1)&255; this.nz(this.y); used=2; break; case 0x88: this.y=(this.y-1)&255; this.nz(this.y); used=2; break;
    case 0x4c: this.pc=this.abs(); used=3; break; case 0x6c: {const a=this.abs(), lo=this.bus.read(a), hi=this.bus.read((a&0xff00)|((a+1)&255)); this.pc=lo|(hi<<8); used=5; break;} case 0x20: {const d=this.abs(); this.push((this.pc-1)>>>8); this.push(this.pc-1); this.pc=d; used=6; break;}
    case 0x60: this.pc=(this.pop()|(this.pop()<<8))+1; used=6; break; case 0x00: this.pc=(this.pc+1)&0xffff; this.push(this.pc>>>8); this.push(this.pc); this.push(this.p|B|U); this.p|=I; this.pc=this.read16(0xfffe); used=7; break; case 0x40: this.p=(this.pop()|U)&~B; this.pc=this.pop()|(this.pop()<<8); used=6; break; case 0x68: this.a=this.pop(); this.nz(this.a); used=4; break; case 0x08: this.push(this.p|B|U); used=3; break; case 0x28: this.p=(this.pop()|U)&~B; used=4; break;
    case 0x69: this.adc(this.imm()); used=2; break; case 0xe9: this.adc(this.imm()^255); used=2; break; case 0x65: this.adc(this.bus.read(this.fetch())); used=3; break; case 0x75: this.adc(this.bus.read(this.zpx())); used=4; break; case 0x6d: this.adc(this.bus.read(this.abs())); used=4; break; case 0x7d: this.adc(this.bus.read(this.absx())); used=4; break; case 0x79: this.adc(this.bus.read(this.absy())); used=4; break; case 0x61: this.adc(this.bus.read(this.indX())); used=6; break; case 0x71: this.adc(this.bus.read(this.indY())); used=5; break; case 0xe5: this.adc(this.bus.read(this.fetch())^255); used=3; break; case 0xf5: this.adc(this.bus.read(this.zpx())^255); used=4; break; case 0xed: this.adc(this.bus.read(this.abs())^255); used=4; break; case 0xfd: this.adc(this.bus.read(this.absx())^255); used=4; break; case 0xf9: this.adc(this.bus.read(this.absy())^255); used=4; break; case 0xe1: this.adc(this.bus.read(this.indX())^255); used=6; break; case 0xf1: this.adc(this.bus.read(this.indY())^255); used=5; break;
    case 0x29: this.a&=this.imm(); this.nz(this.a); used=2; break; case 0x24: {const v=this.bus.read(this.fetch()); this.p=(this.p&~(N|V|Z))|(v&128)|((v&64)?V:0)|((this.a&v)?0:Z); used=3; break;} case 0x2c: {const v=this.bus.read(this.abs()); this.p=(this.p&~(N|V|Z))|(v&128)|((v&64)?V:0)|((this.a&v)?0:Z); used=4; break;} case 0x09: this.a|=this.imm(); this.nz(this.a); used=2; break; case 0x49: this.a^=this.imm(); this.nz(this.a); used=2; break; case 0x31: this.a&=this.bus.read(this.indY()); this.nz(this.a); used=5; break; case 0x11: this.a|=this.bus.read(this.indY()); this.nz(this.a); used=5; break; case 0x51: this.a^=this.bus.read(this.indY()); this.nz(this.a); used=5; break; case 0x3d: this.a&=this.bus.read(this.absx()); this.nz(this.a); used=4; break; case 0x1d: this.a|=this.bus.read(this.absx()); this.nz(this.a); used=4; break; case 0x5d: this.a^=this.bus.read(this.absx()); this.nz(this.a); used=4; break; case 0x39: this.a&=this.bus.read(this.absy()); this.nz(this.a); used=4; break; case 0x19: this.a|=this.bus.read(this.absy()); this.nz(this.a); used=4; break; case 0x59: this.a^=this.bus.read(this.absy()); this.nz(this.a); used=4; break; case 0x21: this.a&=this.bus.read(this.indX()); this.nz(this.a); used=6; break; case 0x01: this.a|=this.bus.read(this.indX()); this.nz(this.a); used=6; break; case 0x41: this.a^=this.bus.read(this.indX()); this.nz(this.a); used=6; break; case 0x25: this.a&=this.bus.read(this.fetch()); this.nz(this.a); used=3; break; case 0x05: this.a|=this.bus.read(this.fetch()); this.nz(this.a); used=3; break; case 0x45: this.a^=this.bus.read(this.fetch()); this.nz(this.a); used=3; break; case 0x35: this.a&=this.bus.read(this.zpx()); this.nz(this.a); used=4; break; case 0x15: this.a|=this.bus.read(this.zpx()); this.nz(this.a); used=4; break; case 0x55: this.a^=this.bus.read(this.zpx()); this.nz(this.a); used=4; break; case 0x2d: this.a&=this.bus.read(this.abs()); this.nz(this.a); used=4; break; case 0x0d: this.a|=this.bus.read(this.abs()); this.nz(this.a); used=4; break; case 0x4d: this.a^=this.bus.read(this.abs()); this.nz(this.a); used=4; break;
    case 0xc9: this.compare(this.a,this.imm()); used=2; break; case 0xc5: this.compare(this.a,this.bus.read(this.fetch())); used=3; break; case 0xd5: this.compare(this.a,this.bus.read(this.zpx())); used=4; break; case 0xcd: this.compare(this.a,this.bus.read(this.abs())); used=4; break; case 0xdd: this.compare(this.a,this.bus.read(this.absx())); used=4; break; case 0xd9: this.compare(this.a,this.bus.read(this.absy())); used=4; break; case 0xc1: this.compare(this.a,this.bus.read(this.indX())); used=6; break; case 0xd1: this.compare(this.a,this.bus.read(this.indY())); used=5; break; case 0xe0: this.compare(this.x,this.imm()); used=2; break; case 0xc0: this.compare(this.y,this.imm()); used=2; break; case 0xe4: this.compare(this.x,this.bus.read(this.fetch())); used=3; break; case 0xec: this.compare(this.x,this.bus.read(this.abs())); used=4; break; case 0xc4: this.compare(this.y,this.bus.read(this.fetch())); used=3; break; case 0xcc: this.compare(this.y,this.bus.read(this.abs())); used=4; break;
    case 0x85: this.bus.write(this.fetch(),this.a); used=3; break; case 0x86: this.bus.write(this.fetch(),this.x); used=3; break; case 0x84: this.bus.write(this.fetch(),this.y); used=3; break;
    case 0xa5: this.a=this.bus.read(this.fetch()); this.nz(this.a); used=3; break; case 0xa6: this.x=this.bus.read(this.fetch()); this.nz(this.x); used=3; break; case 0xa4: this.y=this.bus.read(this.fetch()); this.nz(this.y); used=3; break;
    case 0x1a: break; case 0x3a: break; case 0x80: this.fetch(); used=2; break; case 0x82: this.fetch(); used=2; break; case 0x89: this.fetch(); used=2; break; case 0xc2: this.fetch(); used=2; break; case 0xe2: this.fetch(); used=2; break; case 0xe6: {const a=this.fetch(),v=(this.bus.read(a)+1)&255; this.bus.write(a,v); this.nz(v); used=5; break;} case 0xc6: {const a=this.fetch(),v=(this.bus.read(a)-1)&255; this.bus.write(a,v); this.nz(v); used=5; break;} case 0xee: {const a=this.abs(),v=(this.bus.read(a)+1)&255; this.bus.write(a,v); this.nz(v); used=6; break;} case 0xf6: {const a=this.zpx(),v=(this.bus.read(a)+1)&255; this.bus.write(a,v); this.nz(v); used=6; break;} case 0xce: {const a=this.abs(),v=(this.bus.read(a)-1)&255; this.bus.write(a,v); this.nz(v); used=6; break;} case 0xd6: {const a=this.zpx(),v=(this.bus.read(a)-1)&255; this.bus.write(a,v); this.nz(v); used=6; break;}
    case 0x0a: this.a=this.shift(this.a, false); used=2; break; case 0x4a: this.a=this.shift(this.a, true); used=2; break; case 0x2a: this.a=this.rotate(this.a, false); used=2; break; case 0x6a: this.a=this.rotate(this.a, true); used=2; break; case 0x06: {const a=this.fetch();this.bus.write(a,this.shift(this.bus.read(a),false));used=5;break;} case 0x46: {const a=this.fetch();this.bus.write(a,this.shift(this.bus.read(a),true));used=5;break;} case 0x26: {const a=this.fetch();this.bus.write(a,this.rotate(this.bus.read(a),false));used=5;break;} case 0x66: {const a=this.fetch();this.bus.write(a,this.rotate(this.bus.read(a),true));used=5;break;} case 0x0e: {const a=this.abs();this.bus.write(a,this.shift(this.bus.read(a),false));used=6;break;} case 0x4e: {const a=this.abs();this.bus.write(a,this.shift(this.bus.read(a),true));used=6;break;} case 0x2e: {const a=this.abs();this.bus.write(a,this.rotate(this.bus.read(a),false));used=6;break;} case 0x6e: {const a=this.abs();this.bus.write(a,this.rotate(this.bus.read(a),true));used=6;break;} case 0x16: {const a=this.zpx();this.bus.write(a,this.shift(this.bus.read(a),false));used=6;break;} case 0x56: {const a=this.zpx();this.bus.write(a,this.shift(this.bus.read(a),true));used=6;break;} case 0x36: {const a=this.zpx();this.bus.write(a,this.rotate(this.bus.read(a),false));used=6;break;} case 0x76: {const a=this.zpx();this.bus.write(a,this.rotate(this.bus.read(a),true));used=6;break;} case 0x1e: {const a=this.absx();this.bus.write(a,this.shift(this.bus.read(a),false));used=7;break;} case 0x5e: {const a=this.absx();this.bus.write(a,this.shift(this.bus.read(a),true));used=7;break;} case 0x3e: {const a=this.absx();this.bus.write(a,this.rotate(this.bus.read(a),false));used=7;break;} case 0x7e: {const a=this.absx();this.bus.write(a,this.rotate(this.bus.read(a),true));used=7;break;}
    case 0xaa: this.x=this.a; this.nz(this.x); used=2; break; case 0xba: this.x=this.sp; this.nz(this.x); used=2; break; case 0x9a: this.sp=this.x; used=2; break; case 0x48: this.push(this.a); used=3; break; case 0x8a: this.a=this.x; this.nz(this.a); used=2; break; case 0xa8: this.y=this.a; this.nz(this.y); used=2; break; case 0x98: this.a=this.y; this.nz(this.a); used=2; break;
    case 0x18: this.p&=~C; used=2; break; case 0x90: used=this.branch(!(this.p&C)); break; case 0xb0: used=this.branch(!!(this.p&C)); break; case 0x50: used=this.branch(!(this.p&V)); break; case 0x70: used=this.branch(!!(this.p&V)); break;  case 0x38: this.p|=C; used=2; break; case 0x58: this.p&=~I; used=2; break; case 0x78: this.p|=I; used=2; break; case 0xb8: this.p&=~V; used=2; break; case 0xd8: this.p&=~D; used=2; break; case 0xf8: this.p|=D; used=2; break;
    case 0xd0: used=this.branch(!(this.p&Z)); break; case 0xf0: used=this.branch(!!(this.p&Z)); break; case 0x10: used=this.branch(!(this.p&N)); break; case 0x30: used=this.branch(!!(this.p&N)); break;
    case 0x07: this.slo(this.fetch()); used=5; break; case 0x0f: this.slo(this.abs()); used=6; break; case 0x17: this.slo(this.zpx()); used=6; break; case 0x1f: this.slo(this.absx()); used=7; break; case 0x13: this.slo(this.indY()); used=8; break;
    case 0x27: this.rla(this.fetch()); used=5; break; case 0x2f: this.rla(this.abs()); used=6; break; case 0x37: this.rla(this.zpx()); used=6; break; case 0x3f: this.rla(this.absx()); used=7; break; case 0x33: this.rla(this.indY()); used=8; break;
    case 0x47: this.sre(this.fetch()); used=5; break; case 0x4f: this.sre(this.abs()); used=6; break; case 0x57: this.sre(this.zpx()); used=6; break; case 0x5f: this.sre(this.absx()); used=7; break;
    case 0x67: this.rra(this.fetch()); used=5; break; case 0x6f: this.rra(this.abs()); used=6; break; case 0x77: this.rra(this.zpx()); used=6; break; case 0x7f: this.rra(this.absx()); used=7; break;
    case 0xc7: this.dcp(this.fetch()); used=5; break; case 0xcf: this.dcp(this.abs()); used=6; break; case 0xd7: this.dcp(this.zpx()); used=6; break; case 0xdf: this.dcp(this.absx()); used=7; break;
    case 0xe7: this.isc(this.fetch()); used=5; break; case 0xef: this.isc(this.abs()); used=6; break; case 0xf7: this.isc(this.zpx()); used=6; break; case 0xfe: {const a=this.absx(),v=(this.bus.read(a)+1)&255;this.bus.write(a,v);this.nz(v);used=7;break;} case 0xff: this.isc(this.absx()); used=7; break;
    case 0x80: this.fetch(); used=2; break; case 0x82: this.fetch(); used=2; break; case 0x89: this.fetch(); used=2; break; case 0xc2: this.fetch(); used=2; break; case 0xe2: this.fetch(); used=2; break; case 0xeb: this.adc(this.imm()^255); used=2; break; case 0xbf: this.a=this.x=this.bus.read(this.absy()); this.nz(this.a); used=4; break; case 0x03: {const a=this.indX();const v=this.shift(this.bus.read(a),false);this.bus.write(a,v);this.a|=v;this.nz(this.a);used=8;break;} case 0x0b: case 0x2b: {const v=this.imm();this.p=(this.p&~(N|V|Z))|(v&128)|((v&64)?V:0)|((this.a&v)?0:Z);this.p=(this.p&~C)|(v&128?C:0);this.a&=v;this.nz(this.a);used=2;break;} case 0xdc: this.absx();used=4;break; case 0xfb: this.isc(this.absy());used=7;break; case 0xf3: this.isc(this.indY());used=8;break; case 0xfc: this.absx();used=4;break; case 0x54: this.zpx();used=4;break; case 0x34: this.zpx();used=4;break; case 0x83: {this.bus.write(this.indX(),this.a&this.x);used=6;break;} case 0xde: {const a=this.absx(),v=(this.bus.read(a)+1)&255;this.bus.write(a,v);this.adc(v^255);used=7;break;} case 0xda: break; case 0xfa: break; case 0x5a: break; case 0x7a: break; case 0xf4: this.zpx(); used=4; break; case 0x74: this.zpx(); used=4; break; case 0x32: this.indX(); used=2; break; case 0xd4: this.zpx(); used=4; break;
    default: this.unknownOpcodes++; this.lastUnknownOpcode=op; this.unknownOpcodeCounts[op]++; used=2; break;
  } this.cycles+=used; return used; }
  private fetch(){const v=this.bus.read(this.pc); this.pc=(this.pc+1)&0xffff; return v;}
  private imm(){const v=this.fetch(); this.nz(v); return v;}
  private abs(){const lo=this.fetch(), hi=this.fetch(); return lo|(hi<<8);}
  private absx(){return (this.abs()+this.x)&0xffff;} private absy(){return (this.abs()+this.y)&0xffff;}
  private zpx(){return (this.fetch()+this.x)&255;} private zpy(){return (this.fetch()+this.y)&255;}
  private indX(){const a=(this.fetch()+this.x)&255; return this.bus.read(a)|(this.bus.read((a+1)&255)<<8);}
  private indY(){const a=this.fetch(), base=this.bus.read(a)|(this.bus.read((a+1)&255)<<8); return (base+this.y)&0xffff;}
  private read16(a:number){return this.bus.read(a)|(this.bus.read((a+1)&0xffff)<<8);}
  private interrupt(vector:number){this.push(this.pc>>>8); this.push(this.pc); this.push(this.p&~B|U); this.p|=I; this.pc=this.read16(vector); this.cycles+=7;}
  private push(v:number){this.bus.write(0x100|this.sp,v); this.sp=(this.sp-1)&255;}
  private pop(){this.sp=(this.sp+1)&255; return this.bus.read(0x100|this.sp);}
  private nz(v:number){this.p=(this.p&~(N|Z))|(v?0:Z)|(v&128);}
  private slo(a:number){const v=this.shift(this.bus.read(a),false);this.bus.write(a,v);this.a|=v;this.nz(this.a);}
  private rla(a:number){const v=this.rotate(this.bus.read(a),false);this.bus.write(a,v);this.a&=v;this.nz(this.a);}
  private sre(a:number){const v=this.shift(this.bus.read(a),true); this.bus.write(a,v); this.a^=v; this.nz(this.a);}
  private rra(a:number){const v=this.rotate(this.bus.read(a),true); this.bus.write(a,v); this.adc(v);}
  private dcp(a:number){const v=(this.bus.read(a)-1)&255; this.bus.write(a,v); this.compare(this.a,v);}
  private isc(a:number){const v=(this.bus.read(a)+1)&255; this.bus.write(a,v); this.adc(v^255);}
  private shift(v:number,right:boolean){this.p=(this.p&~C)|(right?(v&1):((v>>7)&1)); v=right?v>>1:(v<<1)&255; this.nz(v); return v;}
  private rotate(v:number,right:boolean){const c=this.p&C?1:0; this.p=(this.p&~C)|(right?(v&1):((v>>7)&1)); v=right?(v>>1)|(c<<7):((v<<1)&255)|c; this.nz(v); return v;}
  private compare(reg:number,v:number){const d=(reg-v)&255; this.p=(this.p&~C)|(reg>=v?C:0); this.nz(d);}
  private adc(v:number){const sum=this.a+v+(this.p&C?1:0); this.p=(this.p&~(C|V))|(sum>255?C:0)|((~(this.a^v)&(this.a^sum)&128)?V:0); this.a=sum&255; this.nz(this.a);}
  private branch(ok:boolean){if(!ok)return 2; const off=(this.fetch()<<24)>>24; const old=this.pc; this.pc=(this.pc+off)&0xffff; return 3 + ((old & 0xff00) !== (this.pc & 0xff00) ? 1 : 0);}
}
