import { parseRom, RomImage } from './rom.js';
import { Cpu6502, CpuBus } from './cpu.js';
import { Controller } from './controller.js';
import { Ppu } from './ppu.js';
export interface Frame { readonly pixels: Uint32Array; readonly width: 256; readonly height: 240; }
export class Nes implements CpuBus { readonly controller1 = new Controller(); readonly ppu = new Ppu(); readonly controller2 = new Controller(); readonly rom: RomImage; get frame(): Uint32Array { return this.ppu.frame; } readonly cpu: Cpu6502; private readonly ram = new Uint8Array(0x800); private cycles = 0; private dmaStall = 0; private mmc1Shift=0x10; private mmc1Control=0x0c; private mmc1Chr0=0; private mmc1Chr1=0; private mmc1Prg=0; private bank = 0;
  constructor(image: ArrayBuffer | Uint8Array) { this.rom=parseRom(image); if(this.rom.mapper!==0&&this.rom.mapper!==1&&this.rom.mapper!==2) throw new Error(`Unsupported mapper: ${this.rom.mapper}`); this.ppu.setMirroring(this.rom.mirroring); this.ppu.setChr(this.rom.chrRam?new Uint8Array(0x2000):this.rom.chrRom); this.cpu=new Cpu6502(this); }
  read(address:number){address&=0xffff; if(address<0x2000)return this.ram[address&0x7ff]; if(address>=0x2000 && address<0x4000)return this.ppu.readRegister(address); if(address===0x4016)return this.controller1.read(); if(address===0x4017)return this.controller2.read(); if(address>=0x8000){ if(this.rom.mapper===1){const bankSize=0x4000, banks=this.rom.prgRom.length/bankSize, mode=(this.mmc1Control>>2)&3, b=this.mmc1Prg&(banks-1); let i; if(mode<2)i=((b&~1)*bankSize)+(address-0x8000); else i=address<0xc000?((mode===2?0:b)*bankSize+address-0x8000):((mode===3?b:b|1)*bankSize+address-0xc000); return this.rom.prgRom[i%this.rom.prgRom.length]; } if(this.rom.mapper===2){const bankSize=0x4000; const bankCount=this.rom.prgRom.length/bankSize; const i=address<0xc000 ? this.bank%bankCount*bankSize+address-0x8000 : (bankCount-1)*bankSize+address-0xc000; return this.rom.prgRom[i]; } const i=address-0x8000; return this.rom.prgRom[i%this.rom.prgRom.length];} return 0;}
  write(address:number,value:number){if(address>=0x2000 && address<0x4000){this.ppu.writeRegister(address,value); return;} if(address<0x2000)this.ram[address&0x7ff]=value&255; else if(address===0x4016){this.controller1.write(value); this.controller2.write(value);} else if(address===0x4014){this.dmaStall += 513; const page=(value&255)<<8; const bytes=new Uint8Array(256); for(let i=0;i<256;i++)bytes[i]=this.read(page+i); this.ppu.dma(bytes);} else if(address>=0x8000 && this.rom.mapper===2)this.bank=value&255; else if(address>=0x8000 && this.rom.mapper===1){if(value&0x80){this.mmc1Shift=0x10; this.mmc1Control|=0x0c;} else {const done=this.mmc1Shift&1; this.mmc1Shift=(this.mmc1Shift>>1)|((value&1)<<4); if(done){const r=(address>>13)&3; if(r===0)this.mmc1Control=this.mmc1Shift&31; else if(r===3)this.mmc1Prg=this.mmc1Shift&31; this.mmc1Shift=0x10;}}}}
  reset(){this.ram.fill(0); this.bank=0; this.dmaStall=0; this.ppu.frame.fill(0xff000000); this.cpu.reset(); this.cycles=0;}
  step(cycles=1){if(!Number.isInteger(cycles)||cycles<1)throw new RangeError('cycles must be a positive integer'); while(this.cycles<cycles){if(this.dmaStall){const used=Math.min(this.dmaStall,cycles-this.cycles); this.dmaStall-=used; this.cycles+=used; this.ppu.step(used*3); continue;} const used=this.cpu.step(); this.cycles+=used; this.ppu.step(used*3);}}
  saveState(): Uint8Array { const out=new Uint8Array(11+0x800); out.set(this.cpu.save()); out.set(this.ram,11); return out; }
  loadState(state: Uint8Array): void { if(state.length!==11+0x800) throw new RangeError('Invalid state size'); this.cpu.load(Array.from(state.slice(0,11))); this.ram.set(state.slice(11)); }
  runFrame():Frame{this.step(29780); return {pixels:this.frame,width:256,height:240};} get cycleCount(){return this.cycles;}
}
